### ISSUE TITLE
Temporary children in codemodule.module.Module.get()

### ISSUE THREAD

**Issue by jkmartindale** [zopefoundation/zope.app.apidoc#20]
`get()` at around [line 247 in `module.py`](https://github.com/zopefoundation/zope.app.apidoc/blob/master/src/zope/app/apidoc/codemodule/module.py#L247) will create and return a child if it's not in the current namespace but can be safely imported. As noted in the nearby comments, the child is temporary and isn't held onto after it is returned.

From what I've seen, this results in a package's entire module tree being rebuilt every single time one of its members is traversed, which is a large waste of CPU time and memory especially with large packages.

Is there a reason the transient child isn't stored to the current Module's `_children`, thus building the module tree only once?

**Comment by jamadden** [comment]
The only transient children that should be getting built are root modules not explicitly listed as a root module in configuration. I see this on `builtins` and `abc` and `logging`, for example. These should all be getting traversed to from the `CodeModule` object, aka the `IDocumentationModule` named `Code`, which has no actual backing Python module.

The reason they're not stored is that it wouldn't really help. Each time we traverse down through `@@apidoc`,  we create a *new* instance of the `CodeModule` utility with a new `_children` array (`apidoc.APIDocumentation.get()` calls `CodeModule.withParentAndName()`) because the `@@apidoc` `APIDocumentation` object could be traversed to from anywhere.

I think there's a good argument to be made for *not* allowing traversal into unregistered root modules altogether. They're not listed in the menus, so it's hard to find them, and they're better documented on https://docs.python.org than they would be here. If you really want them, you can explicitly register them as a root module in ZCML.

The problem is that simply having the traversal raise a KeyError at that point results in a 500 internal server error, so something else needs to be looking to handle that case (not sure where yet).
